#!/bin/bash

print_help(){
    echo "Hello! Proper usage of this is as follows:"
    echo "dhjasklfhfclip \"FILE_PATH\" START END OUT_NAME"
}

if [ ${1,,} = help ]; then
    print_help
    exit 1
fi

FILE_PATH="/mnt/e/"$(sed 's/\\/\//g' <<< ${1} | cut -c 4-)
START=$(echo ${2} | awk -F: '{ print ($1 * 60) + $2 }')
END=$(echo ${3} | awk -F: '{ print (($1 * 60) + $2) }')
OUT_NAME=${4}".webm"

debug(){
    echo "file path: $FILE_PATH"
    echo "start: $START"
    echo "end: $END"
    echo "out name: $OUT_NAME"
}
debug

ffmpeg -ss $START -to $END -i "$FILE_PATH" -c:v libvpx-vp9 -b:v 0 -crf 30 -map_chapters -1 -pass 1 -an -sn -f null /dev/null && \
    ffmpeg -ss $START -to $END -i "$FILE_PATH" -c:v libvpx-vp9 -b:v 0 -crf 30 -map_chapters -1 -pass 2 -c:a libopus -b:a 192k -sn $OUT_NAME
